### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by takura247** [alimirzaei/TSFS#1]
Hi,

Thanks for sharing the code. However, when I try to run the code,  it seems that the 'AEFS_final.py' and 'mnist_model.py' are missing. Could you please upload those files?

Thanks!

**Comment by alimirzaei** [comment]
They are other methods which I compared TSFS with them. You can comment these methods and run the TSFS method.

**Comment by takura247** [comment]
OK, thanks.

**Comment by alimirzaei** [comment]
I added my MNIST model to the repository
